# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


- np.zeros((2, 3))會產生真正的0
- np.empty((2, 3))會產生一個近似0的陣列
- np.empty可用於只是想初始化，但之後就會數值覆寫的情況

In [1]:
import numpy as np
# np.zeros 和 np.empty 
# 真正的0陣列
print(np.zeros((2, 3)))
# 接近0的陣列
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [2]:
# 記得先 Import 正確的套件

import numpy as np


In [32]:
# 參考解答

a = np.random.rand(2, 3)
a *= 100
print(a)

[[78.64253666 22.93742729 47.56079059]
 [70.62010329 18.21757571 31.07836439]]


In [33]:
print(a.round())
print(np.round(a))

[[79. 23. 48.]
 [71. 18. 31.]]
[[79. 23. 48.]
 [71. 18. 31.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [24]:
m = 20
n = 40

a = np.random.rand(2, 3)*(n - m)
b = a

print((a-b % 1 + m))


[[39. 28. 33.]
 [35. 27. 21.]]


In [9]:
a = np.random.rand(2, 3)
a

array([[0.98974853, 0.00792812, 0.2477606 ],
       [0.33763867, 0.39537091, 0.5031187 ]])

In [10]:
a * (n -m)

array([[19.79497067,  0.15856241,  4.95521196],
       [ 6.75277338,  7.90741828, 10.06237403]])