# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
# 記得先 Import 正確的套件

import numpy as np

In [16]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a[(3<=a) & (a<=6)] *=-1
a

array([ 1,  2, -3, -4, -5, -6,  7,  8,  9, 10])

In [17]:
np.where([(3<=a) & (a<=6)], -a, a)

array([[ 1,  2, -3, -4, -5, -6,  7,  8,  9, 10]])

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [23]:
A = np.random.rand(3, 6)
print(A[A>0.5])
print(A[A>0.5].size)

[0.82976315 0.95109863 0.67108783 0.96828232 0.77983598 0.58000898]
6
